### ISSUE TITLE
Watch app broken

### ISSUE THREAD

**Issue by elrod16** [Sichroteph/Weather-Graph#2]
The latest build will launch but never make it past the refresh/loading screen. Rolling back to the previous version fixes the issue.

Pebble Time Steel
Android 11

**Comment by Sichroteph** [comment]
Thanks for your feedback. It seems that sometimes, the API key fails to change/register.
I just published a new build that does not change much but is working well on my side, can you try it ?
Also if it still doesn't work, you can try to reinstall the app completely, it helped with some users.

**Comment by elrod16** [comment]
That did the trick, thanks for the speedy fix.

**Comment by Sichroteph** [comment]
Glad to help !
